### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: 'ablations/evaluation_ids.json'

### ISSUE THREAD

**Issue by monacv** [jasonyzhang/annotator#1]
Hi Jason,

Could you please share with me the json file (jalal@bu.edu) ?

```
(phosa) mona@goku:~/research/code/annotator$ python app.py
Traceback (most recent call last):
  File "app.py", line 17, in <module>
    with open(osp.join(DATA_DIR, "evaluation_ids.json")) as f:
FileNotFoundError: [Errno 2] No such file or directory: 'ablations/evaluation_ids.json'

```

![Screenshot from 2021-03-16 00-26-26](https://user-images.githubusercontent.com/76495162/111255905-58980300-85ee-11eb-95ce-7823bfb48cdf.png)

**Comment by monacv** [comment]
actually, i found the file you linked but I am not seeing anything to compare against.
https://raw.githubusercontent.com/facebookresearch/phosa/master/doc/evaluation_ids.json
However, I am still a bit lost 
![Screenshot from 2021-03-16 00-34-54](https://user-images.githubusercontent.com/76495162/111256483-8df12080-85ef-11eb-8e93-4bb45d6bc5a4.png)
![Screenshot from 2021-03-16 00-34-38](https://user-images.githubusercontent.com/76495162/111256485-8e89b700-85ef-11eb-8d46-3f66194fc13f.png)
![Screenshot from 2021-03-16 00-34-31](https://user-images.githubusercontent.com/76495162/111256486-8e89b700-85ef-11eb-8721-735d17963bfb.png)

**Comment by monacv** [comment]
@jasonyzhang  thank you so much for providing me with the files. This is very interesting research.

So for the images below, they seem equal to me. Is that a sensible choice to you?
![Screenshot from 2021-03-16 17-38-58](https://user-images.githubusercontent.com/76495162/111383448-9a708a00-867e-11eb-9a94-7f0a7679fcea.png)

**Comment by jasonyzhang** [comment]
Thanks @monacv!

The projections of both image look reasonable, but in the top-down view, the bat on the left is floating in the air, but the bat on the right is properly in the batter's hands, so I would say the right image is more reasonable
