### ISSUE TITLE
Is "collision" term considered for images in the "interaction" category for qualitative testing?

### ISSUE THREAD

**Issue by monacv** [jasonyzhang/annotator#2]
I have a question regarding this image.

When you have created the following 3D models, have you included the "collision" term? Since in one of them the hand is colliding with the tennis racket while these images are under the "interaction" category.

![Screenshot from 2021-03-16 17-48-15](https://user-images.githubusercontent.com/76495162/111385331-0227d480-8681-11eb-9e64-0283b75332e3.png)

**Comment by jasonyzhang** [comment]
The collision term is considered in both.
